### ISSUE TITLE
Set up actions/workflow for web hooks from other openMINDS repositories

### ISSUE THREAD

**Issue by ehennestad** [openMetadataInitiative/openMINDS_MATLAB#10]
Set up separate workflows for web hooks to the following repositories:

openMINDS_Documentation
openMINDS_Instances

Each action should ideally be triggered by a push or PR to one of these repositories.

@olinux

**Comment by ehennestad** [comment]
Added workflow for running test if updates are made to openMINDS_Documentation:
https://github.com/openMetadataInitiative/openMINDS_MATLAB/blob/pipeline/.github/workflows/test_doclinks.yml

This should be triggered on a push or PR to the pipeline branch of openMINDS_Documentation.

I'll tag you as well @lzehl

**Comment by ehennestad** [comment]
As far as I understand, we would have to add a new workflow to the openMINDS_Documentation repository:

trigger_target_repositories.yml

```
name: Trigger target repositories

on:
  # Triggers the workflow on push or pull request events for the "pipeline" branch
  push:
    branches: [ "pipeline" ]
  pull_request:
    branches: [ "pipeline" ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger target repositories
      run: |
        curl -XPOST -u "${{secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/openMetadataInitiative/openMINDS_MATLAB/actions/workflows/test_doclinks.yml/dispatches --data '{"ref": "pipeline"}'
```
